/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Software_Development;

import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author lawka
 */
public class Guard_Account extends javax.swing.JFrame {

    private int userId;

    /**
     * Creates new form Guard_Account
     */
    public Guard_Account(int userId) {
        initComponents();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperWhiteBar = new javax.swing.JPanel();
        Title1 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Register = new javax.swing.JButton();
        Second1 = new javax.swing.JPanel();
        ResidentName1 = new javax.swing.JLabel();
        insertId = new javax.swing.JTextField();
        Second2 = new javax.swing.JPanel();
        ResidentName2 = new javax.swing.JLabel();
        insertPass = new javax.swing.JPasswordField();
        guardRegister = new javax.swing.JButton();
        Namebg = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Resident = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Payment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpperWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        UpperWhiteBar.setPreferredSize(new java.awt.Dimension(363, 65));

        Title1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Title1.setText("Create Guard Account");

        javax.swing.GroupLayout UpperWhiteBarLayout = new javax.swing.GroupLayout(UpperWhiteBar);
        UpperWhiteBar.setLayout(UpperWhiteBarLayout);
        UpperWhiteBarLayout.setHorizontalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperWhiteBarLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Title1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperWhiteBarLayout.setVerticalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperWhiteBarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Title1)
                .addGap(22, 22, 22))
        );

        Background.setBackground(new java.awt.Color(153, 153, 153));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        Register.setBackground(new java.awt.Color(235, 235, 235));
        Register.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Register.setText("Register");
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        Second1.setPreferredSize(new java.awt.Dimension(299, 30));

        ResidentName1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ResidentName1.setText("Guard Id:");

        javax.swing.GroupLayout Second1Layout = new javax.swing.GroupLayout(Second1);
        Second1.setLayout(Second1Layout);
        Second1Layout.setHorizontalGroup(
            Second1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Second1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertId, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        Second1Layout.setVerticalGroup(
            Second1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Second1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(insertId)
        );

        Second2.setPreferredSize(new java.awt.Dimension(299, 30));

        ResidentName2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ResidentName2.setText("Password:");

        insertPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertPassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Second2Layout = new javax.swing.GroupLayout(Second2);
        Second2.setLayout(Second2Layout);
        Second2Layout.setHorizontalGroup(
            Second2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Second2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertPass, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Second2Layout.setVerticalGroup(
            Second2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Second2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(insertPass)
        );

        guardRegister.setBackground(new java.awt.Color(235, 235, 235));
        guardRegister.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        guardRegister.setText("Resident Register");
        guardRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Second1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
            .addComponent(Second2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(Register)
                        .addGap(138, 138, 138))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(guardRegister)
                        .addGap(104, 104, 104))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Second1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(Second2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Register)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guardRegister)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Name.setText("Guard");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Software_Development/img/rsz_guard.png"))); // NOI18N

        javax.swing.GroupLayout NamebgLayout = new javax.swing.GroupLayout(Namebg);
        Namebg.setLayout(NamebgLayout);
        NamebgLayout.setHorizontalGroup(
            NamebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamebgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(NamebgLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NamebgLayout.setVerticalGroup(
            NamebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamebgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Resident.setBackground(new java.awt.Color(235, 235, 235));
        Resident.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Resident.setText("Home");
        Resident.setPreferredSize(new java.awt.Dimension(83, 45));
        Resident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentActionPerformed(evt);
            }
        });

        Account.setBackground(new java.awt.Color(153, 153, 153));
        Account.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Account.setText("Account");
        Account.setPreferredSize(new java.awt.Dimension(83, 45));
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(235, 235, 235));
        Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Search.setText("Resident");
        Search.setPreferredSize(new java.awt.Dimension(83, 45));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Payment.setBackground(new java.awt.Color(235, 235, 235));
        Payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Payment.setText("Visitor");
        Payment.setPreferredSize(new java.awt.Dimension(83, 45));
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(Namebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Namebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        try {
            String url = "jdbc:mysql://localhost:3306/aps";
            String username = "root";
            String dbpassword = "";
            Connection connection = null;

            // Open connection
            connection = DriverManager.getConnection(url, username, dbpassword);

            //String id = insertId.getText();
            String id = insertId.getText();
            String guardPassword = insertPass.getText();
            String encryptedpassword = null;

            /* MessageDigest instance for MD5. */
            MessageDigest m = MessageDigest.getInstance("MD5");

            /* Add plain-text password bytes to digest using MD5 update() method. */
            m.update(guardPassword.getBytes());

            /* Convert the hash value into bytes */
            byte[] bytes = m.digest();

            /* The bytes array has bytes in decimal form. Converting it into hexadecimal format. */
            StringBuilder s = new StringBuilder();
            for (int i = 0; i < bytes.length; i++) {
                s.append(Integer.toString((bytes[i] & 0xff) + 0x100, 16).substring(1));
            }

            /* Complete hashed password in hexadecimal format */
            encryptedpassword = s.toString();

            // Check if the ID already exists in the Guard table
            String checkExistingIdQuery = "SELECT * FROM guard WHERE id = ?";
            PreparedStatement checkExistingIdStatement = connection.prepareStatement(checkExistingIdQuery);
            checkExistingIdStatement.setString(1, id);
            ResultSet existingIdResult = checkExistingIdStatement.executeQuery();

            if (existingIdResult.next()) {
                // If the ID already exists, show an error message
                JOptionPane.showMessageDialog(this, "Guard ID already exists. Please choose a different ID.");
                insertId.setText("");
                insertPass.setText("");
            } else {
                // If the ID doesn't exist, insert the new record             
                String insertQuery = "INSERT INTO guard ( password, id) VALUES ( ?, ?)";
                PreparedStatement insertStatement = connection.prepareStatement(insertQuery);
                insertStatement.setString(1, encryptedpassword);
                insertStatement.setString(2, id);
                int rowsAffected = insertStatement.executeUpdate();

                if (rowsAffected > 0) {
                    // Registration successful, show message
                    JOptionPane.showMessageDialog(this, "Registration completed");
                    insertId.setText("");
                    insertPass.setText("");
                } else {
                    // Registration failed, show error message
                    JOptionPane.showMessageDialog(this, "Registration failed. Please try again.");
                    insertId.setText("");
                    insertPass.setText("");
                }
            }

            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void insertPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertPassActionPerformed

    private void ResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentActionPerformed
        // TODO add your handling code here:
        dispose();
        Manager_Home account = new Manager_Home(userId);
        account.setVisible(true);
    }//GEN-LAST:event_ResidentActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
//        dispose();
//        Resident_Account account = new Resident_Account();
//        account.setVisible(true);
    }//GEN-LAST:event_AccountActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        dispose();
        Resident_Search search = new Resident_Search(userId);
        search.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        Manager_VisitorInfo account = new Manager_VisitorInfo(userId);
        account.setVisible(true);
        dispose();
    }//GEN-LAST:event_PaymentActionPerformed

    private void guardRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardRegisterActionPerformed
        // TODO add your handling code here:
        dispose();
        Resident_Account account = new Resident_Account(userId);
        account.setVisible(true);
    }//GEN-LAST:event_guardRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guard_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guard_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guard_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guard_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            int userId = 123;

            public void run() {
                new Guard_Account(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Namebg;
    private javax.swing.JButton Payment;
    private javax.swing.JButton Register;
    private javax.swing.JButton Resident;
    private javax.swing.JLabel ResidentName1;
    private javax.swing.JLabel ResidentName2;
    private javax.swing.JButton Search;
    private javax.swing.JPanel Second1;
    private javax.swing.JPanel Second2;
    private javax.swing.JLabel Title1;
    private javax.swing.JPanel UpperWhiteBar;
    private javax.swing.JButton guardRegister;
    private javax.swing.JTextField insertId;
    private javax.swing.JPasswordField insertPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
