/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Software_Development;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author JingXuan
 */
public class Manager_Forum2 extends javax.swing.JFrame {

    private int userId;

    
    public Manager_Forum2(int userId) {
        this.userId = userId;
        initComponents();
        
        try {
            String url = "jdbc:mysql://localhost:3306/aps";
            String username = "root";
            String dbpassword = "";
            Connection connection = null;
            connection = DriverManager.getConnection(url, username, dbpassword);
            
            String sql = "SELECT forum_id, title FROM management_forum";
            PreparedStatement statement = connection.prepareStatement(sql);
            
            ResultSet resultSet = statement.executeQuery(); //problem here
            // Process the result
            while (resultSet.next()) {
                String id = resultSet.getString("forum_id");
                String titles = resultSet.getString("title");
                
                //add string array for storing data into jtable
                String tbData[] = {id, titles};
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                
                //add string array data into jtable
                tblModel.addRow(tbData);
            }
            
            resultSet.close();
            statement.close();
            connection.close();

        } catch (Exception e) {
            //System.out.println("Failed to connect to the database!");
            JOptionPane.showMessageDialog(this, e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        page_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        forum_type = new javax.swing.JToggleButton();
        forum_create = new javax.swing.JButton();
        LowerWhiteBar = new javax.swing.JPanel();
        Visitor = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        Resident = new javax.swing.JButton();
        Home = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Forum");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        page_title.setBackground(new java.awt.Color(255, 255, 255));
        page_title.setForeground(new java.awt.Color(255, 255, 255));
        page_title.setText("Management");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Forum Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        forum_type.setText("Resident");
        forum_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forum_typeActionPerformed(evt);
            }
        });

        forum_create.setText("Create");
        forum_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forum_createActionPerformed(evt);
            }
        });

        LowerWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        LowerWhiteBar.setPreferredSize(new java.awt.Dimension(0, 57));

        Visitor.setBackground(new java.awt.Color(235, 235, 235));
        Visitor.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Visitor.setText("Visitor");
        Visitor.setPreferredSize(new java.awt.Dimension(83, 45));
        Visitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitorActionPerformed(evt);
            }
        });

        Account.setBackground(new java.awt.Color(235, 235, 235));
        Account.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Account.setText("Account");
        Account.setPreferredSize(new java.awt.Dimension(83, 45));
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        Resident.setBackground(new java.awt.Color(153, 153, 153));
        Resident.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Resident.setText("Resident");
        Resident.setPreferredSize(new java.awt.Dimension(83, 45));
        Resident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentActionPerformed(evt);
            }
        });

        Home.setBackground(new java.awt.Color(235, 235, 235));
        Home.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Home.setText("Home");
        Home.setPreferredSize(new java.awt.Dimension(83, 45));
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LowerWhiteBarLayout = new javax.swing.GroupLayout(LowerWhiteBar);
        LowerWhiteBar.setLayout(LowerWhiteBarLayout);
        LowerWhiteBarLayout.setHorizontalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Visitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LowerWhiteBarLayout.setVerticalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Visitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(forum_type, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(page_title, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addComponent(forum_create)
                        .addGap(16, 16, 16))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LowerWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(page_title)
                            .addComponent(forum_type))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(forum_create)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(LowerWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();

        TableModel model = jTable1.getModel();

        String id = model.getValueAt(index, 0).toString();
        int forumId = Integer.parseInt(id);

        if (forum_type.isSelected()) {
            Manager_Forum_Content2 obj= new Manager_Forum_Content2(userId, forumId);// obj created for class Second()
            obj.setVisible(true); // Open the Second.java window
            dispose(); // Close the First.java window
        }
        else {
            Manager_Forum_Content2 obj= new Manager_Forum_Content2(userId, forumId);// obj created for class Second()
            obj.setVisible(true); // Open the Second.java window
            dispose(); // Close the First.java window
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void forum_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forum_typeActionPerformed
        if (forum_type.isSelected()) {
            
            page_title.setText("Resident");
            forum_create.setEnabled(false);
            try {
                String url = "jdbc:mysql://localhost:3306/aps";
                String username = "root";
                String dbpassword = "";
                Connection connection = null;
                connection = DriverManager.getConnection(url, username, dbpassword);

                String sql = "SELECT forum_id, title FROM resident_forum";
                PreparedStatement statement = connection.prepareStatement(sql);
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);

                ResultSet resultSet = statement.executeQuery(); //problem here
                // Process the result
                while (resultSet.next()) {
                    String id = resultSet.getString("forum_id");
                    String titles = resultSet.getString("title");

                    //add string array for storing data into jtable
                    String tbData[] = {id, titles};
                    //add string array data into jtable
                    tblModel.addRow(tbData);
                }

                resultSet.close();
                statement.close();
                connection.close();

            } catch (Exception e) {
                //System.out.println("Failed to connect to the database!");
                JOptionPane.showMessageDialog(this, e);
                e.printStackTrace();
            }    
        }
        else {
            page_title.setText("Management");
            forum_create.setEnabled(true);
            
                try {
                String url = "jdbc:mysql://localhost:3306/aps";
                String username = "root";
                String dbpassword = "";
                Connection connection = null;
                connection = DriverManager.getConnection(url, username, dbpassword);
                
            String sql = "SELECT forum_id, title FROM management_forum";
                PreparedStatement statement = connection.prepareStatement(sql);
                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);

                ResultSet resultSet = statement.executeQuery();
                // Process the result
                while (resultSet.next()) {
                    String id = resultSet.getString("forum_id");
                    String titles = resultSet.getString("title");

                    //add string array for storing data into jtable
                    String tbData[] = {id, titles};

                    //add string array data into jtable
                    tblModel.addRow(tbData);
                }

                resultSet.close();
                statement.close();
                connection.close();

            } catch (Exception e) {
                //System.out.println("Failed to connect to the database!");
                JOptionPane.showMessageDialog(this, e);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_forum_typeActionPerformed

    private void forum_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forum_createActionPerformed
        Manager_Forum_Creation2 obj= new Manager_Forum_Creation2(userId);// obj created for class Second()
        obj.setVisible(true); // Open the Second.java window
        dispose(); // Close the First.java window
    }//GEN-LAST:event_forum_createActionPerformed

    private void VisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisitorActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        Resident_Account account = new Resident_Account(userId);
        account.setVisible(true);
        dispose();
    }//GEN-LAST:event_AccountActionPerformed

    private void ResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentActionPerformed
        Resident_Search search = new Resident_Search(userId);
        search.setVisible(true);
        dispose();
    }//GEN-LAST:event_ResidentActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Manager_Home home = new Manager_Home(userId);
        home.setVisible(true);
        dispose();
    }//GEN-LAST:event_HomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        if (args.length < 1) {
            System.out.println("Usage: java Software_Development.Resident_Profile <userId>");
            System.exit(1);
        }

        int userId = Integer.parseInt(args[0]);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manager_Forum2(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JButton Home;
    private javax.swing.JPanel LowerWhiteBar;
    private javax.swing.JButton Resident;
    private javax.swing.JButton Visitor;
    private javax.swing.JButton forum_create;
    private javax.swing.JToggleButton forum_type;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel page_title;
    // End of variables declaration//GEN-END:variables
}
