package Software_Development;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JingXuan
 */
public class Resident_Account extends javax.swing.JFrame {

    /**
     * Creates new form Resident_Account
     */
    public Resident_Account() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperWhiteBar = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        First5 = new javax.swing.JPanel();
        UnitNo5 = new javax.swing.JLabel();
        Second = new javax.swing.JPanel();
        ResidentName = new javax.swing.JLabel();
        Third = new javax.swing.JPanel();
        VehicleNumber = new javax.swing.JLabel();
        Fourth = new javax.swing.JPanel();
        Email = new javax.swing.JLabel();
        Fifth = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Namebg = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LowerWhiteBar = new javax.swing.JPanel();
        Resident = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Payment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpperWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        UpperWhiteBar.setPreferredSize(new java.awt.Dimension(363, 65));

        Title.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Title.setText("Create Resident Account");

        javax.swing.GroupLayout UpperWhiteBarLayout = new javax.swing.GroupLayout(UpperWhiteBar);
        UpperWhiteBar.setLayout(UpperWhiteBarLayout);
        UpperWhiteBarLayout.setHorizontalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperWhiteBarLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperWhiteBarLayout.setVerticalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpperWhiteBarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Title)
                .addGap(22, 22, 22))
        );

        Background.setBackground(new java.awt.Color(153, 153, 153));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        First5.setPreferredSize(new java.awt.Dimension(299, 30));

        UnitNo5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        UnitNo5.setText("Unit No :");

        javax.swing.GroupLayout First5Layout = new javax.swing.GroupLayout(First5);
        First5.setLayout(First5Layout);
        First5Layout.setHorizontalGroup(
            First5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(First5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UnitNo5)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        First5Layout.setVerticalGroup(
            First5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(First5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UnitNo5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Second.setPreferredSize(new java.awt.Dimension(299, 30));

        ResidentName.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        ResidentName.setText("Resident Name :");

        javax.swing.GroupLayout SecondLayout = new javax.swing.GroupLayout(Second);
        Second.setLayout(SecondLayout);
        SecondLayout.setHorizontalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SecondLayout.setVerticalGroup(
            SecondLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ResidentName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Third.setPreferredSize(new java.awt.Dimension(299, 30));

        VehicleNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        VehicleNumber.setText("Vehicle Number :");

        javax.swing.GroupLayout ThirdLayout = new javax.swing.GroupLayout(Third);
        Third.setLayout(ThirdLayout);
        ThirdLayout.setHorizontalGroup(
            ThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VehicleNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ThirdLayout.setVerticalGroup(
            ThirdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VehicleNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fourth.setPreferredSize(new java.awt.Dimension(299, 30));

        Email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Email.setText("E-mail :");

        javax.swing.GroupLayout FourthLayout = new javax.swing.GroupLayout(Fourth);
        Fourth.setLayout(FourthLayout);
        FourthLayout.setHorizontalGroup(
            FourthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Email)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FourthLayout.setVerticalGroup(
            FourthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Email)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Fifth.setPreferredSize(new java.awt.Dimension(299, 30));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Phone Number :");

        javax.swing.GroupLayout FifthLayout = new javax.swing.GroupLayout(Fifth);
        Fifth.setLayout(FifthLayout);
        FifthLayout.setHorizontalGroup(
            FifthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FifthLayout.setVerticalGroup(
            FifthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Register.setBackground(new java.awt.Color(235, 235, 235));
        Register.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Register.setText("Register");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Second, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(Fourth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(Fifth, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addComponent(Third, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(Register)
                        .addGap(0, 117, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(First5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Third, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fourth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fifth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register)
                .addContainerGap())
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(First5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        Name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Name.setText("Resident");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JingXuan\\Documents\\NetBeansProjects\\JFrameSoftwareDevelopment(JX)\\src\\Software_Development\\img\\apm.png")); // NOI18N

        javax.swing.GroupLayout NamebgLayout = new javax.swing.GroupLayout(Namebg);
        Namebg.setLayout(NamebgLayout);
        NamebgLayout.setHorizontalGroup(
            NamebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamebgLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamebgLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        NamebgLayout.setVerticalGroup(
            NamebgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamebgLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LowerWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        LowerWhiteBar.setPreferredSize(new java.awt.Dimension(0, 57));

        Resident.setBackground(new java.awt.Color(235, 235, 235));
        Resident.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Resident.setText("Resident");
        Resident.setPreferredSize(new java.awt.Dimension(83, 45));
        Resident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentActionPerformed(evt);
            }
        });

        Account.setBackground(new java.awt.Color(153, 153, 153));
        Account.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Account.setText("Account");
        Account.setPreferredSize(new java.awt.Dimension(83, 45));
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(235, 235, 235));
        Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Search.setText("Search");
        Search.setPreferredSize(new java.awt.Dimension(83, 45));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Payment.setBackground(new java.awt.Color(235, 235, 235));
        Payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Payment.setText("Payment");
        Payment.setPreferredSize(new java.awt.Dimension(83, 45));
        Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LowerWhiteBarLayout = new javax.swing.GroupLayout(LowerWhiteBar);
        LowerWhiteBar.setLayout(LowerWhiteBarLayout);
        LowerWhiteBarLayout.setHorizontalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LowerWhiteBarLayout.setVerticalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(Namebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(LowerWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(Namebg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(LowerWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResidentActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        Resident_Account account = new Resident_Account();
        account.setVisible(true);
    }//GEN-LAST:event_AccountActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        Resident_Search search = new Resident_Search();
        search.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentActionPerformed
        Resident_Payment payment = new Resident_Payment();
        payment.setVisible(true);
    }//GEN-LAST:event_PaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resident_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resident_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resident_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resident_Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resident_Account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Email;
    private javax.swing.JPanel Fifth;
    private javax.swing.JPanel First5;
    private javax.swing.JPanel Fourth;
    private javax.swing.JPanel LowerWhiteBar;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Namebg;
    private javax.swing.JButton Payment;
    private javax.swing.JButton Register;
    private javax.swing.JButton Resident;
    private javax.swing.JLabel ResidentName;
    private javax.swing.JButton Search;
    private javax.swing.JPanel Second;
    private javax.swing.JPanel Third;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel UnitNo5;
    private javax.swing.JPanel UpperWhiteBar;
    private javax.swing.JLabel VehicleNumber;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
