package Software_Development;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author JingXuan
 */
public class Resident_Payment extends javax.swing.JFrame {

    /**
     * Creates new form Resident_Payment
     */
    public Resident_Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpperWhiteBar = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        LowerWhiteBar = new javax.swing.JPanel();
        Resident = new javax.swing.JButton();
        Account = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        Payment = new javax.swing.JButton();
        Background = new javax.swing.JPanel();
        TopBar = new javax.swing.JPanel();
        UnitNo = new javax.swing.JLabel();
        BillsType = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Payment2 = new javax.swing.JLabel();
        No2 = new javax.swing.JPanel();
        var6 = new javax.swing.JLabel();
        var7 = new javax.swing.JLabel();
        var8 = new javax.swing.JLabel();
        var9 = new javax.swing.JLabel();
        var10 = new javax.swing.JLabel();
        Reminder1 = new javax.swing.JButton();
        No1 = new javax.swing.JPanel();
        var1 = new javax.swing.JLabel();
        var2 = new javax.swing.JLabel();
        var3 = new javax.swing.JLabel();
        var4 = new javax.swing.JLabel();
        var5 = new javax.swing.JLabel();
        Reminder2 = new javax.swing.JButton();
        No3 = new javax.swing.JPanel();
        var11 = new javax.swing.JLabel();
        var12 = new javax.swing.JLabel();
        var13 = new javax.swing.JLabel();
        var14 = new javax.swing.JLabel();
        var15 = new javax.swing.JLabel();
        Reminder3 = new javax.swing.JButton();
        No4 = new javax.swing.JPanel();
        var16 = new javax.swing.JLabel();
        var17 = new javax.swing.JLabel();
        var18 = new javax.swing.JLabel();
        var19 = new javax.swing.JLabel();
        var20 = new javax.swing.JLabel();
        Reminder4 = new javax.swing.JButton();
        GeneratePaymentRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UpperWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        UpperWhiteBar.setPreferredSize(new java.awt.Dimension(363, 65));

        Title.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        Title.setText("Payment Info");

        javax.swing.GroupLayout UpperWhiteBarLayout = new javax.swing.GroupLayout(UpperWhiteBar);
        UpperWhiteBar.setLayout(UpperWhiteBarLayout);
        UpperWhiteBarLayout.setHorizontalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperWhiteBarLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpperWhiteBarLayout.setVerticalGroup(
            UpperWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpperWhiteBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Title)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        LowerWhiteBar.setBackground(new java.awt.Color(255, 255, 255));
        LowerWhiteBar.setPreferredSize(new java.awt.Dimension(0, 57));

        Resident.setBackground(new java.awt.Color(235, 235, 235));
        Resident.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Resident.setText("Resident");
        Resident.setPreferredSize(new java.awt.Dimension(83, 45));
        Resident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResidentActionPerformed(evt);
            }
        });

        Account.setBackground(new java.awt.Color(235, 235, 235));
        Account.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Account.setText("Account");
        Account.setPreferredSize(new java.awt.Dimension(83, 45));
        Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountActionPerformed(evt);
            }
        });

        Search.setBackground(new java.awt.Color(235, 235, 235));
        Search.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Search.setText("Search");
        Search.setPreferredSize(new java.awt.Dimension(83, 45));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Payment.setBackground(new java.awt.Color(153, 153, 153));
        Payment.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Payment.setText("Payment");
        Payment.setPreferredSize(new java.awt.Dimension(83, 45));

        javax.swing.GroupLayout LowerWhiteBarLayout = new javax.swing.GroupLayout(LowerWhiteBar);
        LowerWhiteBar.setLayout(LowerWhiteBarLayout);
        LowerWhiteBarLayout.setHorizontalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        LowerWhiteBarLayout.setVerticalGroup(
            LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LowerWhiteBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LowerWhiteBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Resident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Account, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Background.setBackground(new java.awt.Color(153, 153, 153));

        TopBar.setBackground(new java.awt.Color(153, 153, 153));

        UnitNo.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        UnitNo.setText("Unit No");

        BillsType.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        BillsType.setText("Bills Type");

        Date.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        Date.setText("Date");

        Payment2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        Payment2.setText("Payment");

        javax.swing.GroupLayout TopBarLayout = new javax.swing.GroupLayout(TopBar);
        TopBar.setLayout(TopBarLayout);
        TopBarLayout.setHorizontalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(UnitNo)
                .addGap(18, 18, 18)
                .addComponent(BillsType)
                .addGap(18, 18, 18)
                .addComponent(Date)
                .addGap(18, 18, 18)
                .addComponent(Payment2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBarLayout.setVerticalGroup(
            TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(TopBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnitNo)
                    .addComponent(BillsType)
                    .addComponent(Date)
                    .addComponent(Payment2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        No2.setBackground(new java.awt.Color(255, 255, 255));

        var6.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var6.setText("1");

        var7.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var7.setText("XXX");

        var8.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var8.setText("XXX");

        var9.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var9.setText("XXX");

        var10.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var10.setText("XXX");

        Reminder1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Reminder1.setText("Reminder");

        No1.setBackground(new java.awt.Color(255, 255, 255));

        var1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var1.setText("2");

        var2.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var2.setText("XXX");

        var3.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var3.setText("XXX");

        var4.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var4.setText("XXX");

        var5.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var5.setText("XXX");

        Reminder2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Reminder2.setText("Reminder");

        javax.swing.GroupLayout No1Layout = new javax.swing.GroupLayout(No1);
        No1.setLayout(No1Layout);
        No1Layout.setHorizontalGroup(
            No1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(var1)
                .addGap(34, 34, 34)
                .addComponent(var2)
                .addGap(41, 41, 41)
                .addComponent(var3)
                .addGap(36, 36, 36)
                .addComponent(var4)
                .addGap(38, 38, 38)
                .addComponent(var5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reminder2)
                .addContainerGap())
        );
        No1Layout.setVerticalGroup(
            No1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(No1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var1)
                    .addComponent(var2)
                    .addComponent(var3)
                    .addComponent(var4)
                    .addComponent(var5)
                    .addComponent(Reminder2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No3.setBackground(new java.awt.Color(255, 255, 255));

        var11.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var11.setText("3");

        var12.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var12.setText("XXX");

        var13.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var13.setText("XXX");

        var14.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var14.setText("XXX");

        var15.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var15.setText("XXX");

        Reminder3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Reminder3.setText("Reminder");

        javax.swing.GroupLayout No3Layout = new javax.swing.GroupLayout(No3);
        No3.setLayout(No3Layout);
        No3Layout.setHorizontalGroup(
            No3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(var11)
                .addGap(34, 34, 34)
                .addComponent(var12)
                .addGap(40, 40, 40)
                .addComponent(var13)
                .addGap(38, 38, 38)
                .addComponent(var14)
                .addGap(37, 37, 37)
                .addComponent(var15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reminder3)
                .addContainerGap())
        );
        No3Layout.setVerticalGroup(
            No3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(No3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var11)
                    .addComponent(var12)
                    .addComponent(var13)
                    .addComponent(var14)
                    .addComponent(var15)
                    .addComponent(Reminder3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No4.setBackground(new java.awt.Color(255, 255, 255));

        var16.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var16.setText("4");

        var17.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var17.setText("XXX");

        var18.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var18.setText("XXX");

        var19.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var19.setText("XXX");

        var20.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        var20.setText("XXX");

        Reminder4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Reminder4.setText("Reminder");

        javax.swing.GroupLayout No4Layout = new javax.swing.GroupLayout(No4);
        No4.setLayout(No4Layout);
        No4Layout.setHorizontalGroup(
            No4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(var16)
                .addGap(33, 33, 33)
                .addComponent(var17)
                .addGap(41, 41, 41)
                .addComponent(var18)
                .addGap(37, 37, 37)
                .addComponent(var19)
                .addGap(38, 38, 38)
                .addComponent(var20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reminder4)
                .addContainerGap())
        );
        No4Layout.setVerticalGroup(
            No4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(No4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var16)
                    .addComponent(var17)
                    .addComponent(var18)
                    .addComponent(var19)
                    .addComponent(var20)
                    .addComponent(Reminder4))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout No2Layout = new javax.swing.GroupLayout(No2);
        No2.setLayout(No2Layout);
        No2Layout.setHorizontalGroup(
            No2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(var6)
                .addGap(35, 35, 35)
                .addComponent(var7)
                .addGap(40, 40, 40)
                .addComponent(var8)
                .addGap(37, 37, 37)
                .addComponent(var9)
                .addGap(37, 37, 37)
                .addComponent(var10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Reminder1)
                .addContainerGap())
            .addComponent(No1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(No3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(No4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        No2Layout.setVerticalGroup(
            No2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(No2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(var6)
                    .addComponent(var7)
                    .addComponent(var8)
                    .addComponent(var9)
                    .addComponent(var10)
                    .addComponent(Reminder1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(No1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(No4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        GeneratePaymentRecord.setBackground(new java.awt.Color(235, 235, 235));
        GeneratePaymentRecord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        GeneratePaymentRecord.setText("Generate Payment Record");
        GeneratePaymentRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratePaymentRecordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(GeneratePaymentRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(No2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(TopBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(No2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(GeneratePaymentRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpperWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LowerWhiteBar, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(UpperWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LowerWhiteBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResidentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResidentActionPerformed

    private void GeneratePaymentRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratePaymentRecordActionPerformed
        Resident_Payment payment = new Resident_Payment();
        payment.setVisible(true);
    }//GEN-LAST:event_GeneratePaymentRecordActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        Resident_Search search = new Resident_Search();
        search.setVisible(true);
    }//GEN-LAST:event_SearchActionPerformed

    private void AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountActionPerformed
        Resident_Account account = new Resident_Account();
        account.setVisible(true);
    }//GEN-LAST:event_AccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resident_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resident_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resident_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resident_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resident_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Account;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BillsType;
    private javax.swing.JLabel Date;
    private javax.swing.JButton GeneratePaymentRecord;
    private javax.swing.JPanel LowerWhiteBar;
    private javax.swing.JPanel No1;
    private javax.swing.JPanel No2;
    private javax.swing.JPanel No3;
    private javax.swing.JPanel No4;
    private javax.swing.JButton Payment;
    private javax.swing.JLabel Payment2;
    private javax.swing.JButton Reminder1;
    private javax.swing.JButton Reminder2;
    private javax.swing.JButton Reminder3;
    private javax.swing.JButton Reminder4;
    private javax.swing.JButton Resident;
    private javax.swing.JButton Search;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel TopBar;
    private javax.swing.JLabel UnitNo;
    private javax.swing.JPanel UpperWhiteBar;
    private javax.swing.JLabel var1;
    private javax.swing.JLabel var10;
    private javax.swing.JLabel var11;
    private javax.swing.JLabel var12;
    private javax.swing.JLabel var13;
    private javax.swing.JLabel var14;
    private javax.swing.JLabel var15;
    private javax.swing.JLabel var16;
    private javax.swing.JLabel var17;
    private javax.swing.JLabel var18;
    private javax.swing.JLabel var19;
    private javax.swing.JLabel var2;
    private javax.swing.JLabel var20;
    private javax.swing.JLabel var3;
    private javax.swing.JLabel var4;
    private javax.swing.JLabel var5;
    private javax.swing.JLabel var6;
    private javax.swing.JLabel var7;
    private javax.swing.JLabel var8;
    private javax.swing.JLabel var9;
    // End of variables declaration//GEN-END:variables
}
